name: StarRiver_AutoStart
on:
  repository_dispatch:
    types: [start-command]

jobs:
  start_server:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Falix External Start
        run: |
          # 模擬瀏覽器訪問該開機網址
          curl -L -A "Mozilla/5.0" "${{ secrets.START_URL }}"
