name: StarRiver_AutoStart
on:
  repository_dispatch:
    types: [start-command]

jobs:
  start_server:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Falix Start
        run: |
          # 使用 POST 模式並增加模擬瀏覽器的標頭
          curl -X POST "${{ secrets.START_URL }}" \
          -H "Content-Length: 0" \
          -H "Accept: application/json"
