name: StarRiver_AutoStart
on:
  repository_dispatch:
    types: [start-command]

jobs:
  start_server:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Falix
        run: |
          # 模擬瀏覽器去「點擊」那個分享連結
          curl -L -A "Mozilla/5.0" "${{ secrets.START_URL }}"
