name: Auto Start via Falix Link

on:
  repository_dispatch:
    types: [start-command]

jobs:
  ping_falix:
    runs-on: ubuntu-latest
    steps:
      - name: Open Falix Start Link
        run: |
          # 模擬瀏覽器打開你的直達連結
          curl -L "https://falixnodes.net/startserver?ip=ryfn.falix.gg"
